name: 'EKS-Terraform-Validate'

on:
  push:
    branches: 
      - 'feature/terraform'
    paths:
      - 'terraform/eks/**'
      - 'terraform/module/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/eks/**'
      - 'terraform/module/**'

env: 
  AWS_REGION: ap-south-1
  TF_VERSION: 1.9.3

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform Validate & Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform/eks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.9.3
          terraform_wrapper: true

      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check -diff
        continue-on-error: false

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: false

      - name: Terraform Plan
        run: |
          terraform plan -input=false -no-color
        continue-on-error: false